### ISSUE TITLE
TSnode frequency output

### ISSUE THREAD

**Issue by JudGiblin** [CyprienBosserelle/BG_Flood#33]
Hi Cyp, 

Kindly requesting if a timestep frequency can be specified for the TSnode outputs. It's a minor thing really. 
I observed that running an outtimestep=600sec (10min), the TSOfile has an output approximately every 0.1sec. So not really a pressing issue to resolve.

Thanks,
Jud

**Comment by CyprienBosserelle** [comment]
I think this should be a post processing item. 
While not a big deal doing snapshot or mean over a period of time for point output is not trivial within BG_Flood. whereas in a interpreted language t process the output it is trivial. 

Hence I will close this for now.
