### ISSUE TITLE
Add support for a CRS to be encoded in the output files 

### ISSUE THREAD

**Issue by rosepearson** [CyprienBosserelle/BG_Flood#61]
Up to you how you do this, but I think it is important that BG-FLOOD can produce netCDF files with a CRS specified. This could either be:
* Done always - either from a default, or one of the other two options
* Done sometimes - i.e if the user specified a CRS an input in the parameter file
* Done sometimes - i.e. if the input DEM has a defined CRS 

I'd lean to option 1 (always to it) or option 3 (take the CRS from the DEM)

**Comment by rosepearson** [comment]
Hi Team @AliceHarang @CyprienBosserelle 
Here is also the information I pulled together when adding this information to GeoFabrics in a way that you, QGIS and the Python library rioxarray could interoperate.
https://github.com/rosepearson/GeoFabrics/issues/63

**Comment by CyprienBosserelle** [comment]
### This below is suggested in Stackexchange
1. Create a ```crs``` variable
2. Add attribute to ```crs``` that describe the coordinate system
3. use the attribute ```grdimapping``` to associate the variables that contain spatial data to attributes defined under ```crs```


https://gis.stackexchange.com/questions/218441/displaying-netcdf-data-with-correct-crs

**Comment by CyprienBosserelle** [comment]
Thanks Rose. This feature has now been added in v0.9
